Remove the project_name member
The project_name field was confusing: it specified a display name for
the project, the default source/build/install directory name, and the
target name. All of those were set to project_name.lower() by default.

However, a target such as:
class BuildLibXCBRenderUtil(X11AutotoolsProject):
    target = "libxcb-render-util"
    dependencies = ["libxcb"]

would default to using cloning the repository into "libxcbrenderutil"
instead of the expected "libxcb-render-util" since project_name would
be inferred as "LibXCBRenderUtil".

After this commit, the default source/build/install directory name defaults
to the target name and can be overridden by setting a new field,
`default_directory_basename`.

Using the old project_name attribute will now give an error:
.../cheribuild/pycheribuild/projects/cross/x11.py:112: error: project_name should no longer be used, change the definition of class BuildLibXCBImage to specify target=/default_directory_basename