[zcheri] FIXME: use BuildCheriLLVM for llvm_test_suite
./cheribuild --dump-config triggers a CI error as follows, otherwise:

llvm_test_suite.py", line 68, in llvm_project
    return target_info._get_compiler_project()
TypeError: CheriBSDTargetInfo._get_compiler_project() missing 1 required positional argument: 'config'

This is a temp fix