Run pytype with 3.11 instead of 3.12
3.12 fails with:
```
FAILED: /home/runner/work/cheribuild/cheribuild/.pytype/pyi/pycheribuild/projects/cross/drm_kmod.pyi
/opt/hostedtoolcache/Python/3.12.8/x64/bin/python -m pytype.main --disable attribute-error --imports_info /home/runner/work/cheribuild/cheribuild/.pytype/imports/pycheribuild.projects.cross.drm_kmod.imports --module-name pycheribuild.projects.cross.drm_kmod --platform linux -V 3.12 -o /home/runner/work/cheribuild/cheribuild/.pytype/pyi/pycheribuild/projects/cross/drm_kmod.pyi --analyze-annotated --nofail --quick /home/runner/work/cheribuild/cheribuild/pycheribuild/projects/cross/drm_kmod.py
/home/runner/work/cheribuild/cheribuild/pycheribuild/projects/cross/drm_kmod.py:1:1: error: in <module>: Couldn't import pyi for 'cheribsd' [pyi-error]
    File: "/home/runner/work/cheribuild/cheribuild/.pytype/pyi/pycheribuild/projects/cross/cheribsd.pyi", line 56
      .0: Any
     ^
  ParseError: illegal target for annotation

from .cheribsd import BuildFreeBSD
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```