Speculative fix for Jenkins build failure
It appears that _new_tty_foreground_process_group() is raising an
exception, but we only get
`subprocess.SubprocessError: Exception occurred in preexec_fn.` as an
error message which is not very helpful for diagnosing the issue.
This commit attempts to handle the case where open(/dev/tty) fails.
It also adds a new scoped_open() helper function to avoid manual try/finally.


```
Traceback (most recent call last):
  File "./cheribuild/jenkins-cheri-build.py", line 42, in <module>
    pycheribuild.jenkins.jenkins_main()
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/jenkins.py", line 371, in jenkins_main
    run_and_kill_children_on_exit(_jenkins_main)
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/processutils.py", line 671, in run_and_kill_children_on_exit
    fn()
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/jenkins.py", line 275, in _jenkins_main
    build_target(cheri_config, target_manager.get_target_raw(target))
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/jenkins.py", line 313, in build_target
    target.run_tests(cheri_config)
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/targets.py", line 132, in run_tests
    self._do_run(config, msg="Ran tests", func=lambda project: project.run_tests())
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/targets.py", line 112, in _do_run
    func(project)
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/targets.py", line 132, in <lambda>
    self._do_run(config, msg="Ran tests", func=lambda project: project.run_tests())
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/projects/run_qemu.py", line 504, in run_tests
    kernel_path=self.current_kernel)
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/config/compilation_targets.py", line 438, in run_cheribsd_test_script
    self.project.run_cmd(cmd, give_tty_control=True)
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/projects/project.py", line 590, in run_cmd
    no_print=no_print, replace_env=replace_env, give_tty_control=give_tty_control, **kwargs)
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/processutils.py", line 379, in run_command
    with popen_handle_noexec(cmdline, **kwargs) as process:
  File "/local/scratch/jenkins/workspace/CheriBSD-pipeline_PR-937/cheribuild/pycheribuild/processutils.py", line 272, in popen_handle_noexec
    return subprocess.Popen(cmdline, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1365, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.
```