Try to unbreak GitHub CI after actions/setup-python@v2 change
It looks like it no longer has a 3.6 version available:
```
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

Use 3.6.7 which is the oldest version listed in that file.