Silence flake8 warning about nonlocal
F824 Doesn't seem to understand methods of modifying a variable that
aren't direct assignment.

./pycheribuild/projects/run_fvp.py:292:21: F824 `nonlocal extra_args` is unused: name is never assigned in scope
                    nonlocal extra_args
                    ^
./pycheribuild/projects/run_qemu.py:447:13: F824 `nonlocal have_9pfs_support` is unused: name is never assigned in scope
            nonlocal have_9pfs_support
            ^
./pycheribuild/projects/run_qemu.py:448:13: F824 `nonlocal have_smbfs_support` is unused: name is never assigned in scope
            nonlocal have_smbfs_support
            ^
./pycheribuild/projects/run_qemu.py:449:13: F824 `nonlocal qemu_command` is unused: name is never assigned in scope
            nonlocal qemu_command
            ^
4     F824 `nonlocal extra_args` is unused: name is never assigned in scope
Error: Process completed with exit code 1.