Fix AttributeError for __annotations__ with python 3.14
'DefaultCheriConfig' object has no attribute '__annotations__'.
This is because __annotations__ is no longer available on class
instances in newer Python versions. Use inspect.get_annotations()
for newer python versions.