Fix --test causing cheribuild to be suspended
Without this change I get the following after killing QEMU inside the
test script:

[1]+  Stopped                 cheribuild.py cmake-riscv64 --test --interact-after-tests
alex@Alexs-MBP-10:~/devel/cheribuild(master * u=)> fg
cheribuild.py cmake-riscv64 --test --interact-after-tests
Warning: '/Users/alex/devel/cheribuild/test-scripts/run_simple_tests.py --ssh-key /Users/alex/.ssh/id_ed25519.pub --architecture riscv64 --kernel /Users/alex/cheri/output/kernel-riscv64.QEMU-MFS-ROOT --qemu-cmd /Users/alex/cheri/output/sdk/bin/qemu-system-riscv64cheri --build-dir /Users/alex/cheri/build/cmake-crosscompiled-riscv64-build --source-dir /Users/alex/cheri/cmake --sysroot-dir /Users/alex/cheri/output/rootfs-riscv64 --interact --test-command 'cd /build/bin && ./ctest --help' --test-timeout 7200' error while draining: (4, 'Interrupted system call')
Fatal error: Command `/Users/alex/devel/cheribuild/test-scripts/run_simple_tests.py --ssh-key /Users/alex/.ssh/id_ed25519.pub --architecture riscv64 --kernel /Users/alex/cheri/output/kernel-riscv64.QEMU-MFS-ROOT --qemu-cmd /Users/alex/cheri/output/sdk/bin/qemu-system-riscv64cheri --build-dir /Users/alex/cheri/build/cmake-crosscompiled-riscv64-build --source-dir /Users/alex/cheri/cmake --sysroot-dir /Users/alex/cheri/output/rootfs-riscv64 --interact --test-command 'cd /build/bin && ./ctest --help' --test-timeout 7200` failed with non-zero exit code 2. Working directory was /Users/alex/devel/cheribuild